### ISSUE TITLE
how to autocraft iron blocks?

### ISSUE THREAD

**Issue by Jamborger** [QPCrummer/FabricAutoCrafter#10]
im most likely very stupid but when I try to craft iron blocks it just crafts it into nuggets then into blocks

**Comment by QPCrummer** [comment]
You will need to lock the hopper beneath the autocrafter until you have a full autocrafter inventory. I suggest just using a comparator to read the fill level of the autocrafter. If you still need help, let me know!

**Comment by Jamborger** [comment]
oh im kind of an idiot when it comes to redstone lol (I got no clue how to do anything u said)
