### ISSUE TITLE
Melons

### ISSUE THREAD

**Issue by manchesterjm** [QPCrummer/FabricAutoCrafter#11]
This auto crafter does not work with melons, it will not turn slides into melons, it only want to make seeds

**Comment by QPCrummer** [comment]
Did you try locking the hopper below the autocrafter until it fills up with melons? You can use a comparator to detect when the autocrafter fills up completely.

**Comment by manchesterjm** [comment]
yep, standard crafting setup.  It does not do ingots to gold blocks either, but it does do nuggets to ingots.

**Comment by QPCrummer** [comment]
Odd. What version of the mod is this? Latest for 1.20.6? I’ll try to have it fixed in the next hour

**Comment by manchesterjm** [comment]
lastest, ya.  Just downloaded it today from modrinth

**Comment by QPCrummer** [comment]
Ok, I’ll ping you on here when I have a fix. It’s just odd because the main test I do when updating the mod is doing iron -> iron block conversions, and it passed that test

**Comment by manchesterjm** [comment]
ya, I just tried it with iron ingots to blocks and it isn't working there either.  It fills up the table and then just cycles the top left ingot out to the hopper below when the table fills up.

**Comment by manchesterjm** [comment]
![test_two](https://github.com/Tater-Certified/FabricAutoCrafter/assets/24682863/795f4c0b-a8e9-4bb9-9d35-750fd207223b)
![test_one](https://github.com/Tater-Certified/FabricAutoCrafter/assets/24682863/549ab79d-a85b-462b-a178-0a77ac32e90e)
This is what I get when the table is filled.  As you can see the nugget to ingot shows an output, but the ingot to block does not.

**Comment by manchesterjm** [comment]
am I just using it wrong?  Is there a way to set the output I want when there are multiple choices for crafting?

**Comment by QPCrummer** [comment]
You can use an item filter below the autocrafter. That’s what my test uses

**Comment by QPCrummer** [comment]
But ideally it should work regardless of what item extraction method is being used.

**Comment by manchesterjm** [comment]
so when there are a lot of choices for crafting, like in the iron ingot case, how do I tell it I want blocks?

**Comment by QPCrummer** [comment]
You can either use a comparator in subtract mode with a redstone block next to it to detect if the crafter is full, or you can just use a regular item filter to filter only the block.

**Comment by manchesterjm** [comment]
right, but what if I dont want blocks, what if I want buckets, How do I tell the block to craft buckets, or shears, etc...?

**Comment by QPCrummer** [comment]
Those recipes get a bit more complicated because you have to insert filler items where air would normally be, then remove those filler items when the recipe is created. This mod doesn’t really want to be a simple autocrafter mod as I personally don’t like how vanilla’s crafter is so simple and overpowered.

**Comment by manchesterjm** [comment]
ah, ok.  I was looking for something that was like the vanilla one that is coming out in 1.20.1

If this is not supposed to be like that then it looks like I need to find a new mod.

Thanks for letting me know.

**Comment by QPCrummer** [comment]
Yeah, no problem. Thanks for finding that issue though 👍

**Comment by QPCrummer** [comment]
Ok, this issue should be fixed in the latest release: https://modrinth.com/mod/fabricautocrafter/version/1.0.15

**Comment by QPCrummer** [comment]
Actually I'm going to reopen this issue cause it seems like there is still some inconsistencies with it not working all of the time

**Comment by QPCrummer** [comment]
Since we have switched to the vanilla crafting method, this should be fixed
