### ISSUE TITLE
This mod isn't understandable.

### ISSUE THREAD

**Issue by Abu-Maher** [QPCrummer/FabricAutoCrafter#13]
Don't use this mod, It's just the same crafting table, and when you try to place a recipe then puts a hopper underneath, it crafts items you don't want. There's also no wiki explaining how to use it correctly.

**Comment by QPCrummer** [comment]
This mod was developed for the technical Minecraft community, so it works very closely with redstone. You must design a contraption that locks the bottom hopper until your crafting recipe is present in the autocrafter. I suggest using a comparator for this. If you are doing complex crafting recipes (ones with air/empty spaces in the recipe), you will need to use placeholder items, and then remove them before you craft your item. 

I cannot make a generalized tutorial for this mod as the redstone contraption needed to craft items can wildly vary based on the item you want to craft. I can make a simple item -> block autocrafter tutorial if you want.

**Comment by QPCrummer** [comment]
Also this discord server has some designs for my mod: https://discord.gg/guZdbQ9KQe

You can look under the “Carpet Autocrafting Table” section for designs for various items.

**Comment by Ampflower** [comment]
As QPCrummer mentioned; it's intended for use with other redstone components, and predates vanilla's autocrafter by a few years.

You'd want to see videos that uses either this autocrafter or Carpet Autocrafter for general designs, or look at the Discord server.

At the very minimum, if your item of choice isn't just 1 -> ?, use a comparator in comparing mode and use a redstone signal beside it; any complex recipes using air generally requires either: turning the hopper into an item filter in some manner, or with the combination of another mod (i.e. Carpet's pushable block entities rule), moving the crafter over a filter or using a hopper that has a filter built in to remove the placeholders.

Closing as this isn't either a bug or suggestion.
