### ISSUE TITLE
1.19.3 Fabric server, Error on server start.

### ISSUE THREAD

**Issue by greggh** [QPCrummer/FabricAutoCrafter#6]
Hi, thanks for the mod!

I am trying it out on my server, but it doesn't seem to be working. The server finishes starting fine, but this is in the startup log:

29.01 23:49:29 [Server] main/WARN Error loading class: net/minecraft/class_7494 (java.lang.ClassNotFoundException: net/minecraft/class_7494)

It only appears when the fabricautocrafter-1.0.8.jar is in the mods folder on the server.

Because the server still starts, I attempted to craft and use the block anyways. I can craft it with the red stone surrounding a crafting table recipe. It gives me a block named Auto Crafter.

The block looks exactly like a crafting table, and the GUI also looks exactly like a crafting table. I don't see any way to set a recipe for it to use when items are being input.

**Comment by QPCrummer** [comment]
The autocrafter will fill using a dropper or a hopper as an input. It will fill the GUI from top to bottom, left to right. Here is an example by Mumbo Jumbo on how to use the mod https://www.youtube.com/watch?v=n1WCEBdAfQ4

About the error, I've never seen that error. Class_7494 doesn't exist within the MC codebase, so I assume it would be perfectly fine to ignore it.

**Comment by QPCrummer** [comment]
Updating the Polymer I use may fix the class loading error https://modrinth.com/mod/polymer/version/0.3.8+1.19.3

Of course this will only fix it if my older Polymer version is the issue. In the end, if it doesn't fix the issue, the issue can be completely ignored and isn't major at all.

**Comment by Ampflower** [comment]
A full stack trace or crash report would be nice.

Are you using an older version of FabricAutoCrafter on 1.19.3, or any odd mod combinations?

**Comment by QPCrummer** [comment]
@KJP12 Nah, 1.0.8 is the latest. The Polymer version that we are using is a little outdated now, so I wonder if Patbox was relying on something that is no longer present. Maybe in Fabric API or something? We should be fine since we use very little of Polymer.

**Comment by greggh** [comment]
Updated to the latest Polymer, same issue still happening.

@KJP12 I tried it with no other mods (other than fabric and polymer obviously). Same warning issue.

The server isn't generating a crash log for this one, as it continues on past the error, which is only a WARN level,  and finishes loading. 

Edit:

I would also add that the block does seem to be working as intended. After looking at that Mumbo Jumbo video it all makes sense now.

**Comment by QPCrummer** [comment]
Glad to hear that it's working fine. More than likely the error is something to ignore. If you happen to find any issues with it, fee free to reopen the issue and ping me. Have a good day!

**Comment by QPCrummer** [comment]
Ok, I'm fired from GH issue management. KJP is now in charge because I didn't actually fix your issue issue (although I will say that ignoring issues is a good way to fix them (:  )

**Comment by Ampflower** [comment]
If the error annoys you still, v1.0.9 should be ready soon.

As far as I can tell, it's non-critical and all it requires is updating the Server Translations API mod to use the 1.19.3 version.

**Comment by greggh** [comment]
Luckily this was a warning that could be ignored and didn't seem to break anything. But always happy to see a fix!

Thanks for that.

Edit:

For everyone wondering, 1.0.9 does fix the issue.
