### ISSUE TITLE
Is putting in blank spaces just not possible?

### ISSUE THREAD

**Issue by TreeOfSelf** [QPCrummer/FabricAutoCrafter#7]
Say I want to craft a prismarine block using 2x2 prismarine shards, is that just simply not possible?

**Comment by QPCrummer** [comment]
@TreeOfSelf You will need to put in a filler item as the blank spots, then remove them afterwards. You can do this multiple ways:
1. Hopper Minecart filters to remove the filler item
2. Carpet's movable block entities and move it over a filter to remove the filler items

If you need an example of each, just ask!

**Comment by Ampflower** [comment]
On Saturday, 15 April 2023 18:12:05 CDT TreeOfSelf wrote:
> Say I want to craft a prismarine block using 2x2 prismarine shards, is that
> just simply not possible?

It isn't possible to put in blanks, but it is possible to work around it by 
using a hopper with an item filter to remove any random junk item used as 
filler. Although, note, this does require moveable block entities or other mods 
that can extract from any side, as we don't provide that functionality.

Or as QPCrummer has said: Hopper Minecarts is also a decent option if you want
to keep it vanilla.
