### ISSUE TITLE
Mark 1.0.11-1.20 as compatible with 1.20 on Modrinth

### ISSUE THREAD

**Issue by rbits0** [QPCrummer/FabricAutoCrafter#8]
On Modrinth, it says it's only compatible with 1.20-rc1, not 1.20, but it should be because they're the same as far as I'm aware. Useful if you're using Prism Launcher or something similar to download the mod

**Comment by QPCrummer** [comment]
Thanks for saying something. RC1 and 1.20 aren’t technically identical code-wise. Anyways, the Modrinth release now says it is 1.20 compatible. The mod should also be 1.20.1 compatible too when that releases soon
